name: 'DevSecOps'
on: [pull_request]

jobs:
  dependency-submission:
    name: Dependencies submission
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: Gradle Dependency Submission
        uses: mikepenz/gradle-dependency-submission@v0.8.6
        with:
          gradle-project-path: grails532app
  dependency-review:
    name: Dependency review
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: Dependency Review
        uses: actions/dependency-review-action@v3
